# Generated by Django 4.2.30 on 2026-05-09 11:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comorbidity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Comorbidities',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the doctor', max_length=255, verbose_name='Doctor Name')),
                ('contact_no', models.CharField(help_text='Contact number of the doctor', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Contact Number')),
                ('email', models.EmailField(help_text='Email address of the doctor', max_length=254, verbose_name='Email Address')),
                ('highest_qualification', models.CharField(help_text='Highest qualification of the doctor', max_length=255, verbose_name='Highest Qualification')),
                ('specialization', models.CharField(help_text='Specialization of the doctor', max_length=255, verbose_name='Specialization')),
                ('years_of_experience', models.IntegerField(help_text='Years of experience of the doctor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_doctors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First name of the patient', max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Last name of the patient', max_length=255, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(help_text='Date of birth of the patient', verbose_name='Date of Birth')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], help_text='Sex of the patient', max_length=1, verbose_name='Sex')),
                ('contact_no', models.CharField(help_text='Contact number of the patient', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Contact Number')),
                ('email', models.EmailField(help_text='Email address of the patient', max_length=254, unique=True, verbose_name='Email Address')),
                ('type', models.CharField(choices=[('Regular', 'Regular'), ('Free', 'Free')], help_text='Type of the patient', max_length=10, verbose_name='Type')),
                ('date_registered', models.DateField(auto_now_add=True, help_text='Date when the patient was registered', verbose_name='Date Registered')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientMedicalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood group of the patient', max_length=3, verbose_name='Blood Group')),
                ('family_history', models.TextField(blank=True, help_text='Family medical history of the patient', null=True, verbose_name='Family History')),
                ('known_allergies', models.TextField(blank=True, help_text='Known allergies of the patient', null=True, verbose_name='Known Allergies')),
                ('smokes', models.BooleanField(help_text='Whether the patient smokes or not', verbose_name='Smokes')),
                ('alcoholic', models.BooleanField(help_text='Whether the patient is an alcoholic or not', verbose_name='Alcoholic')),
                ('comorbidities', models.ManyToManyField(blank=True, help_text='Comorbidities of the patient', to='app.comorbidity', verbose_name='Comorbidities')),
                ('patient', models.OneToOneField(help_text='Patient associated with the medical information', on_delete=django.db.models.deletion.CASCADE, to='app.patientprofile', verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_file_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('external_file_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file_record', to='app.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDoctorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_assignments', to='app.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_assignments', to='app.patientprofile')),
            ],
            options={
                'verbose_name': 'Patient-Doctor Mapping',
                'unique_together': {('patient', 'doctor')},
            },
        ),
    ]
